app = "tinypilot-pico"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  PS_BEHIND_PROXY = "yes"
  LITESTREAM_BUCKET="picoshare-tinypilot"
  LITESTREAM_ENDPOINT="s3.us-west-000.backblazeb2.com"
  # Backblaze key ID for tinypilot-picoshare. Key is in fly secrets.
  LITESTREAM_ACCESS_KEY_ID = "0004c7a064cefd30000000010"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[build]
  image = "mtlynch/picoshare:1.4.1"

[mounts]
source="pico_data"
destination="/data"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
